services:
  react:
    image: react
    ports:
      - "3000:3000"
    links:
      - spring
  spring:
    image: spring
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=docker_mongo_1
    links:
      - mongo