version: "3.9"
services:
  react:
    build: 
        context: .
        cache_from:
          - react
        dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    environment:
        HOST_IP: "localhost"
    links:
      - spring
  spring:
    build:
        context: .
        cache_from:
          - spring
        dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    environment:
        HOST_IP: "localhost"
    links:
      - mongo
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"