FROM openjdk:17-alpine as spring
RUN apk add git
RUN git clone https://github.com/mateuszlapies/studia.git
WORKDIR studia/ztp/projekt/backend
RUN mv src/main/resources/application.properties.docker src/main/resources/application.properties
RUN chmod u+x mvnw
RUN ./mvnw package -Dmaven.test.skip
ENTRYPOINT ["java", "-jar", "target/backend-dev.jar"]