FROM openjdk:17-alpine as spring
RUN apk add git
RUN git clone https://github.com/mateuszlapies/studia.git
WORKDIR studia/ztp/projekt/backend
COPY init.spring .
RUN chmod u+x init.spring
RUN chmod u+x mvnw
RUN ./mvnw package -Dmaven.test.skip
ENV HOST_IP=localhost
ENTRYPOINT ["init.spring"]