services:
#  react:
#    image: react
#    ports:
#      - "3000:3000"
#    links:
#      - spring
#    image: spring
#    ports:
#      - "8080:8080"
#    links:
#      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /etc/nginx