FROM node:16.13.1-alpine as react
RUN apk add git
RUN git clone https://github.com/mateuszlapies/studia.git
WORKDIR studia/ztp/projekt/frontend
RUN npm install
RUN npm run build
RUN npm install -g serve
ENV HOST_IP=localhost
CMD sed -i "s/host-ip/${HOST_IP}/g" src/config/backend.json
ENTRYPOINT ["serve", "-s", "build"]