FROM node:16.13.1-alpine as react
RUN apk add git
RUN git clone https://github.com/mateuszlapies/studia.git
WORKDIR studia/ztp/projekt/frontend
COPY init.react .
RUN chmod u+x init.react
RUN npm install
RUN npm run build
RUN npm install -g serve
ENV HOST_IP=localhost
ENTRYPOINT ["/bin/ash", "init.react"]